<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ArithmeticError' => $vendorDir . '/symfony/polyfill-php70/Resources/stubs/ArithmeticError.php',
    'AssertionError' => $vendorDir . '/symfony/polyfill-php70/Resources/stubs/AssertionError.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'DivisionByZeroError' => $vendorDir . '/symfony/polyfill-php70/Resources/stubs/DivisionByZeroError.php',
    'Error' => $vendorDir . '/symfony/polyfill-php70/Resources/stubs/Error.php',
    'Normalizer' => $vendorDir . '/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
    'ParseError' => $vendorDir . '/symfony/polyfill-php70/Resources/stubs/ParseError.php',
    'SessionUpdateTimestampHandlerInterface' => $vendorDir . '/symfony/polyfill-php70/Resources/stubs/SessionUpdateTimestampHandlerInterface.php',
    'TypeError' => $vendorDir . '/symfony/polyfill-php70/Resources/stubs/TypeError.php',
    'jonathanraftery\\Bullhorn\\DataStore' => $vendorDir . '/jonathanraftery/bullhorn-auth-client/src/DataStore.php',
    'jonathanraftery\\Bullhorn\\JsonDataStore' => $vendorDir . '/jonathanraftery/bullhorn-auth-client/src/JsonDataStore.php',
    'jonathanraftery\\Bullhorn\\MemoryDataStore' => $vendorDir . '/jonathanraftery/bullhorn-auth-client/src/MemoryDataStore.php',
    'jonathanraftery\\Bullhorn\\Rest\\Authentication\\AuthorizationException' => $vendorDir . '/jonathanraftery/bullhorn-auth-client/src/AuthorizationException.php',
    'jonathanraftery\\Bullhorn\\Rest\\Authentication\\Client' => $vendorDir . '/jonathanraftery/bullhorn-auth-client/src/Client.php',
    'jonathanraftery\\Bullhorn\\Rest\\Authentication\\Exception\\InvalidRefreshTokenException' => $vendorDir . '/jonathanraftery/bullhorn-auth-client/src/InvalidRefreshTokenException.php',
    'jonathanraftery\\Bullhorn\\Rest\\Client' => $vendorDir . '/jonathanraftery/bullhorn-rest-client/src/Client.php',
    'jonathanraftery\\Bullhorn\\Rest\\Resources\\EventSubscription' => $vendorDir . '/jonathanraftery/bullhorn-rest-client/src/Resources/EventSubscription.php',
    'jonathanraftery\\Bullhorn\\Rest\\Resources\\JobOrders' => $vendorDir . '/jonathanraftery/bullhorn-rest-client/src/Resources/JobOrders.php',
    'jonathanraftery\\Bullhorn\\Rest\\Resources\\Resource' => $vendorDir . '/jonathanraftery/bullhorn-rest-client/src/Resources/Resource.php',
    'jonathanraftery\\Bullhorn\\WordpressDataStore' => $vendorDir . '/jonathanraftery/bullhorn-auth-client/src/WordpressDataStore.php',
);
