<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4c4304f3e10d1131a40718b079900b98
{
    public static $files = array (
        '5255c38a0faeba867671b61dfda6d864' => __DIR__ . '/..' . '/paragonie/random_compat/lib/random.php',
        '7b11c4dc42b3b3023073cb14e519683c' => __DIR__ . '/..' . '/ralouphie/getallheaders/src/getallheaders.php',
        '25072dd6e2470089de65ae7bf11d3109' => __DIR__ . '/..' . '/symfony/polyfill-php72/bootstrap.php',
        '023d27dca8066ef29e6739335ea73bad' => __DIR__ . '/..' . '/symfony/polyfill-php70/bootstrap.php',
        'e69f7f6ee287b969198c3c9d6777bd38' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/bootstrap.php',
        'c964ee0ededf28c96ebd9db5099ef910' => __DIR__ . '/..' . '/guzzlehttp/promises/src/functions_include.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        'f598d06aa772fa33d905e87be6398fb1' => __DIR__ . '/..' . '/symfony/polyfill-intl-idn/bootstrap.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
    );

    public static $prefixLengthsPsr4 = array (
        'j' => 
        array (
            'jonathanraftery\\Bullhorn\\REST\\Client\\' => 37,
            'jonathanraftery\\Bullhorn\\REST\\Authentication\\' => 45,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Php72\\' => 23,
            'Symfony\\Polyfill\\Php70\\' => 23,
            'Symfony\\Polyfill\\Intl\\Normalizer\\' => 33,
            'Symfony\\Polyfill\\Intl\\Idn\\' => 26,
        ),
        'P' => 
        array (
            'Psr\\Http\\Message\\' => 17,
        ),
        'L' => 
        array (
            'League\\OAuth2\\Client\\' => 21,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\Promise\\' => 19,
            'GuzzleHttp\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'jonathanraftery\\Bullhorn\\REST\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/jonathanraftery/bullhorn-rest-client/src/Client.php',
        ),
        'jonathanraftery\\Bullhorn\\REST\\Authentication\\' => 
        array (
            0 => __DIR__ . '/..' . '/jonathanraftery/bullhorn-auth-client/src',
        ),
        'Symfony\\Polyfill\\Php72\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php72',
        ),
        'Symfony\\Polyfill\\Php70\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php70',
        ),
        'Symfony\\Polyfill\\Intl\\Normalizer\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer',
        ),
        'Symfony\\Polyfill\\Intl\\Idn\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-idn',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'League\\OAuth2\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/oauth2-client/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
    );

    public static $classMap = array (
        'ArithmeticError' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/ArithmeticError.php',
        'AssertionError' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/AssertionError.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'DivisionByZeroError' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/DivisionByZeroError.php',
        'Error' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/Error.php',
        'Normalizer' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
        'ParseError' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/ParseError.php',
        'SessionUpdateTimestampHandlerInterface' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/SessionUpdateTimestampHandlerInterface.php',
        'TypeError' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/TypeError.php',
        'jonathanraftery\\Bullhorn\\DataStore' => __DIR__ . '/..' . '/jonathanraftery/bullhorn-auth-client/src/DataStore.php',
        'jonathanraftery\\Bullhorn\\JsonDataStore' => __DIR__ . '/..' . '/jonathanraftery/bullhorn-auth-client/src/JsonDataStore.php',
        'jonathanraftery\\Bullhorn\\MemoryDataStore' => __DIR__ . '/..' . '/jonathanraftery/bullhorn-auth-client/src/MemoryDataStore.php',
        'jonathanraftery\\Bullhorn\\Rest\\Authentication\\AuthorizationException' => __DIR__ . '/..' . '/jonathanraftery/bullhorn-auth-client/src/AuthorizationException.php',
        'jonathanraftery\\Bullhorn\\Rest\\Authentication\\Client' => __DIR__ . '/..' . '/jonathanraftery/bullhorn-auth-client/src/Client.php',
        'jonathanraftery\\Bullhorn\\Rest\\Authentication\\Exception\\InvalidRefreshTokenException' => __DIR__ . '/..' . '/jonathanraftery/bullhorn-auth-client/src/InvalidRefreshTokenException.php',
        'jonathanraftery\\Bullhorn\\Rest\\Client' => __DIR__ . '/..' . '/jonathanraftery/bullhorn-rest-client/src/Client.php',
        'jonathanraftery\\Bullhorn\\Rest\\Resources\\EventSubscription' => __DIR__ . '/..' . '/jonathanraftery/bullhorn-rest-client/src/Resources/EventSubscription.php',
        'jonathanraftery\\Bullhorn\\Rest\\Resources\\JobOrders' => __DIR__ . '/..' . '/jonathanraftery/bullhorn-rest-client/src/Resources/JobOrders.php',
        'jonathanraftery\\Bullhorn\\Rest\\Resources\\Resource' => __DIR__ . '/..' . '/jonathanraftery/bullhorn-rest-client/src/Resources/Resource.php',
        'jonathanraftery\\Bullhorn\\WordpressDataStore' => __DIR__ . '/..' . '/jonathanraftery/bullhorn-auth-client/src/WordpressDataStore.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4c4304f3e10d1131a40718b079900b98::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4c4304f3e10d1131a40718b079900b98::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4c4304f3e10d1131a40718b079900b98::$classMap;

        }, null, ClassLoader::class);
    }
}
